force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/recordTypes/Daily.recordType-meta.xml
<RecordType>
    <fullName>Daily</fullName>
    <active>true</active>
    <label>Daily</label>
</RecordType>

force-app/main/default/classes/SendEmailDailyBatch.cls
global class SendEmailDailyBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    @TestVisible static Integer emailLimits;
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, Status__c, Name, RecordType.Name, Employee__c, Employee__r.Name, Employee__r.Email  FROM Task__c WHERE RecordType.Name = \'Daily\' AND Status__c != \'Completed\'';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Task__c> scope){
        Map<String, List<Task__c>> contactTasksMap = new Map<String, List<Task__c>>();
        Map<String, String> contactEmailMap = new Map<String, String>();
        for(Task__c t : scope){
            contactEmailMap.put(t.Employee__c, t.Employee__r.Email);
            if(contactTasksMap.containsKey(t.Employee__c)){
                List<Task__c> tasks = contactTasksMap.get(t.Employee__c);
                tasks.add(t);
                contactTasksMap.put(t.Employee__c, tasks);
            }else{
                contactTasksMap.put(t.Employee__c, new List<Task__c>{t});
            }
        }
        List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
        for(String contact : contactEmailMap.keySet()){
            List<Task__c> tasks = contactTasksMap.get(contact);
            String taskName = '';
            for(Task__c t : tasks){
                taskName += t.Name + '<br/>';
            }         
            Messaging.SingleEmailMessage Message = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[] {contactEmailMap.get(contact)};
            Message.setToAddresses(toAddresses); 
            Message.SaveAsActivity = false;
            Message.setHtmlBody('Hello, <br/><br/>The following daily tasks werent completed today: <br/>' + taskName + '<br/><br/>Regards<br/> Developer');
            mailList.add(Message);
        }

        if(!mailList.isEmpty()) {
            try{
                Messaging.sendEmail(mailList);
            }catch (Exception ex) {
                System.debug('Unable to send email. Here\'s the reason: '+ ex.getStackTraceString());
            }
        }
        emailLimits = Limits.getEmailInvocations();
        
    }  
    global void finish(Database.BatchableContext BC){
        //Chain batches needed.
        //This will prevent any kind of mismatch between the two batches.
        UpdateTasksBatch utb = new UpdateTasksBatch();
        Database.executeBatch(utb,200);
  
    }
  
  

}