force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Habit_Failed__c.field-meta.xml
<CustomField>
    <fullName>Habit_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Habit Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Task_Completed__c.field-meta.xml
<CustomField>
    <fullName>Task_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Task Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task__c/recordTypes/Daily.recordType-meta.xml
<RecordType>
    <fullName>Daily</fullName>
    <active>true</active>
    <label>Daily</label>
</RecordType>

force-app/main/default/objects/Task__c/recordTypes/Habit.recordType-meta.xml
<RecordType>
    <fullName>Habit</fullName>
    <active>true</active>
    <label>Habit</label>
</RecordType>

force-app/main/default/classes/UpdateTasksBatch.cls
global class UpdateTasksBatch implements Database.Batchable<sObject>
{
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, Status__c, Habit_Failed__c, Task_Completed__c, RecordType.Name FROM Task__c WHERE RecordType.Name = \'Daily\' OR RecordType.Name = \'Habit\'';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Task__c> scope){
      
        for(Task__c t : scope){      
            if(t.RecordType.Name == 'Habit'){
                t.Habit_Failed__c = false;
                t.Task_Completed__c = false;
            }else if(t.RecordType.Name == 'Daily'){
                t.Status__c = 'New';
            }
        }
        update scope;
        
    }
      
    global void finish(Database.BatchableContext BC){
        AsyncApexJob job = [SELECT Id, Status FROM AsyncApexJob WHERE Id = :BC.getJobId()];
         //Sending mail about batch status.......
  
    }
  
  

}