force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Habit_Failed__c.field-meta.xml
<CustomField>
    <fullName>Habit_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Habit Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Task_Completed__c.field-meta.xml
<CustomField>
    <fullName>Task_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Task Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task__c/recordTypes/Daily.recordType-meta.xml
<RecordType>
    <fullName>Daily</fullName>
    <active>true</active>
    <label>Daily</label>
</RecordType>

force-app/main/default/objects/Task__c/recordTypes/Habit.recordType-meta.xml
<RecordType>
    <fullName>Habit</fullName>
    <active>true</active>
    <label>Habit</label>
</RecordType>

force-app/main/default/classes/UpdateTasksBatchTest.cls
@isTest
public class UpdateTasksBatchTest {
    @TestSetup
    static void setup(){
        
        String DailyRT = Schema.getGlobalDescribe().get('Task__c').getDescribe().getRecordTypeInfosByName().get('Daily').getRecordTypeId();
        String HabitRT = Schema.getGlobalDescribe().get('Task__c').getDescribe().getRecordTypeInfosByName().get('Habit').getRecordTypeId();

        Contact c = new Contact();
        c.LastName = 'Test Contact';
        c.Email = 'test@test.com';
        insert c;

        List<Task__c> tasks = new List<Task__c>();
        Task__c t = new Task__c();
        t.Name = 'This is an Habit task';
        t.Difficulty__c = 'Easy';
        t.Status__c = 'Completed';
        t.RecordTypeId = DailyRT;
        t.Employee__c = c.Id;
        tasks.add(t);

        Task__c t2 = new Task__c();
        t2.Name = 'This is a ToDo task';
        t2.Difficulty__c = 'Easy';
        t2.Status__c = 'Completed';
        t2.RecordTypeId = DailyRT;
        t2.Employee__c = c.Id;
        tasks.add(t2);

        Task__c t3 = new Task__c();
        t3.Name = 'This is a Daily task';
        t3.Difficulty__c = 'Easy';
        t3.Status__c = 'Completed';
        t3.RecordTypeId = HabitRT;
        t3.Habit_Failed__c = true;
        t3.Task_Completed__c = true;
        t3.Employee__c = c.Id;
        tasks.add(t3);

        insert tasks;
    }
    
    @isTest
    private static void updateTaskBatchTest(){

        Test.startTest();
        UpdateTasksBatch utb = new UpdateTasksBatch();
        Database.executeBatch(utb,200);
        Test.stopTest();

        Task__c t = [SELECT Id, Habit_Failed__c, Task_Completed__c FROM Task__c WHERE RecordType.Name='Habit' LIMIT 1];
        System.assertEquals(false, t.Habit_Failed__c);
        System.assertEquals(false, t.Task_Completed__c);

        Task__c daily = [SELECT Id, Status__c FROM Task__c WHERE RecordType.Name='Daily' LIMIT 1];
        System.assertEquals('New', daily.Status__c);

    }
}