force-app/main/default/objects/Contact/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Points</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>CASE( RecordType.DeveloperName, 
&#39;TO_DO&#39;, (CASE( Difficulty__c , &#39;Trivial&#39;, 1, &#39;Easy&#39;, 2, &#39;Medium&#39;, 3, &#39;Hard&#39;, 5, 0))* IF( Overdue__c, 0.5, 1) , 
&#39;Daily&#39;, (CASE( Difficulty__c , &#39;Trivial&#39;, 0.5, &#39;Easy&#39;, 1, &#39;Medium&#39;, 1.5, &#39;Hard&#39;, 2.5, 0))* IF( Overdue__c, 0, 1), 
&#39;Habit&#39;, 1 - IF(  Habit_Failed__c, 2, 0), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Task_Completed__c.field-meta.xml
<CustomField>
    <fullName>Task_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Task Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task__c/recordTypes/Habit.recordType-meta.xml
<RecordType>
    <fullName>Habit</fullName>
    <active>true</active>
    <label>Habit</label>
</RecordType>

force-app/main/default/classes/CloseTaskTriggerHelper.cls
public with sharing class CloseTaskTriggerHelper {
    
    public static void setTaskCompleted(List<Task__c> tasks) {
        String HabitRT = Schema.getGlobalDescribe().get('Task__c').getDescribe().getRecordTypeInfosByName().get('Habit').getRecordTypeId();
        for(Task__c t : tasks){
            if(t.RecordTypeId != HabitRT){
                if(t.Status__c == 'Completed'){
                    t.Task_Completed__c = true;
                }else{
                    t.Task_Completed__c = false;
                } 
            }   
        }
    }

    public static void setPointsTotals(List<Task__c> tasks){
        String HabitRT = Schema.getGlobalDescribe().get('Task__c').getDescribe().getRecordTypeInfosByName().get('Habit').getRecordTypeId();
        Map<Id, Decimal> contactPointsMap = new Map<Id, Decimal>();
        for(Task__c t : tasks){
            if(t.Status__c == 'Completed'){
                if(contactPointsMap.containsKey(t.Employee__c)){
                    contactPointsMap.put(t.Employee__c, contactPointsMap.get(t.Employee__c)+t.Points__c);
                }else{
                    contactPointsMap.put(t.Employee__c, t.Points__c);
                } 
            }     
        }
        Set<Id> idContacts = contactPointsMap.keySet();
        List<Contact> contactsToUpdate = new List<Contact>();
        for(Id i : idContacts){
            Contact c = [SELECT Id, Total_Points__c FROM Contact WHERE Id =: i];
            if(c.Total_Points__c != null ){
                c.Total_Points__c += contactPointsMap.get(i);
            }else{
                c.Total_Points__c = contactPointsMap.get(i);
            }
            
            contactsToUpdate.add(c);        
        }
        update contactsToUpdate; 
    }
}