force-app/main/default/objects/Contact/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Points</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Habit_Failed__c.field-meta.xml
<CustomField>
    <fullName>Habit_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Habit Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>CASE( RecordType.DeveloperName, 
&#39;TO_DO&#39;, (CASE( Difficulty__c , &#39;Trivial&#39;, 1, &#39;Easy&#39;, 2, &#39;Medium&#39;, 3, &#39;Hard&#39;, 5, 0))* IF( Overdue__c, 0.5, 1) , 
&#39;Daily&#39;, (CASE( Difficulty__c , &#39;Trivial&#39;, 0.5, &#39;Easy&#39;, 1, &#39;Medium&#39;, 1.5, &#39;Hard&#39;, 2.5, 0))* IF( Overdue__c, 0, 1), 
&#39;Habit&#39;, 1 - IF(  Habit_Failed__c, 2, 0), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Task_Completed__c.field-meta.xml
<CustomField>
    <fullName>Task_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Task Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task__c/recordTypes/Daily.recordType-meta.xml
<RecordType>
    <fullName>Daily</fullName>
    <active>true</active>
    <label>Daily</label>
</RecordType>

force-app/main/default/objects/Task__c/recordTypes/Habit.recordType-meta.xml
<RecordType>
    <fullName>Habit</fullName>
    <active>true</active>
    <label>Habit</label>
</RecordType>

force-app/main/default/classes/TaskBoardControllerTest.cls
@isTest
private class TaskBoardControllerTest {
    
    @TestSetup
    static void setup(){
        String HabitRT = Schema.getGlobalDescribe().get('Task__c').getDescribe().getRecordTypeInfosByName().get('Habit').getRecordTypeId();
        String TODORT = Schema.getGlobalDescribe().get('Task__c').getDescribe().getRecordTypeInfosByName().get('TO-DO').getRecordTypeId();
        String DailyRT = Schema.getGlobalDescribe().get('Task__c').getDescribe().getRecordTypeInfosByName().get('Daily').getRecordTypeId();
        
        Contact c = new Contact();
        c.LastName = 'Test Contact';
        insert c;

        List<Task__c> tasks = new List<Task__c>();
        Task__c t = new Task__c();
        t.Name = 'This is an Habit task';
        t.Difficulty__c = 'Easy';
        t.Status__c = 'New';
        t.RecordTypeId = HabitRT;
        t.Employee__c = c.Id;
        tasks.add(t);

        Task__c t2 = new Task__c();
        t2.Name = 'This is a ToDo task';
        t2.Difficulty__c = 'Easy';
        t2.Status__c = 'New';
        t2.RecordTypeId = TODORT;
        t2.Employee__c = c.Id;
        tasks.add(t2);

        Task__c t3 = new Task__c();
        t3.Name = 'This is a Daily task';
        t3.Difficulty__c = 'Easy';
        t3.Status__c = 'New';
        t3.RecordTypeId = DailyRT;
        t3.Employee__c = c.Id;
        tasks.add(t3);

        insert tasks;

    }
    @isTest
    private static void getAllTaskTest(){
        Test.startTest();
        List<Task__c> tasks = TaskBoardController.getAllTasks();
        Test.stopTest();
        System.assertEquals(3, tasks.size());
    }

    @isTest
    private static void setNewStatusTaskTest(){
        Task__c t = [SELECT Id, Status__c FROM Task__c WHERE Status__c != 'In Progress' LIMIT 1];
        Test.startTest();
        TaskBoardController.setNewStatus(t.Id, 'In Progress');
        Test.stopTest();
        System.assertEquals('In Progress', [SELECT Id, Status__c FROM Task__c WHERE Id =: t.Id LIMIT 1].Status__c);
    }

    @isTest
    private static void addHabitPointsTest(){
        Task__c t = [SELECT Id, Employee__c, Points__c FROM Task__c LIMIT 1];
        Test.startTest();
        TaskBoardController.setHabitPoints(t.Id, 'add');
        Test.stopTest();
        System.assert([SELECT Id, Total_Points__c FROM Contact WHERE Id =: t.Employee__c LIMIT 1].Total_Points__c > 0);
        System.assert([SELECT Id, Task_Completed__c FROM Task__c WHERE Id =: t.Id LIMIT 1].Task_Completed__c == true);
    }

    @isTest
    private static void subtractHabitPointsTest(){
        Task__c t = [SELECT Id, Employee__c, Points__c FROM Task__c LIMIT 1];
        Test.startTest();
        TaskBoardController.setHabitPoints(t.Id, 'subtract');
        Test.stopTest();
        System.assert([SELECT Id, Total_Points__c FROM Contact WHERE Id =: t.Employee__c LIMIT 1].Total_Points__c < 0);
        System.assert([SELECT Id, Habit_Failed__c FROM Task__c WHERE Id =: t.Id LIMIT 1].Habit_Failed__c == true);
    }

}