force-app/main/default/objects/Contact/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Points</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>CASE( RecordType.DeveloperName, 
&#39;TO_DO&#39;, (CASE( Difficulty__c , &#39;Trivial&#39;, 1, &#39;Easy&#39;, 2, &#39;Medium&#39;, 3, &#39;Hard&#39;, 5, 0))* IF( Overdue__c, 0.5, 1) , 
&#39;Daily&#39;, (CASE( Difficulty__c , &#39;Trivial&#39;, 0.5, &#39;Easy&#39;, 1, &#39;Medium&#39;, 1.5, &#39;Hard&#39;, 2.5, 0))* IF( Overdue__c, 0, 1), 
&#39;Habit&#39;, 1 - IF(  Habit_Failed__c, 2, 0), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Task_Completed__c.field-meta.xml
<CustomField>
    <fullName>Task_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Task Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task__c/recordTypes/Daily.recordType-meta.xml
<RecordType>
    <fullName>Daily</fullName>
    <active>true</active>
    <label>Daily</label>
</RecordType>

force-app/main/default/objects/Task__c/recordTypes/Habit.recordType-meta.xml
<RecordType>
    <fullName>Habit</fullName>
    <active>true</active>
    <label>Habit</label>
</RecordType>

force-app/main/default/classes/CloseTaskTriggerHelperTest.cls
@isTest
private class CloseTaskTriggerHelperTest {
    
    @TestSetup
    static void setup(){
        String HabitRT = Schema.getGlobalDescribe().get('Task__c').getDescribe().getRecordTypeInfosByName().get('Habit').getRecordTypeId();
        String TODORT = Schema.getGlobalDescribe().get('Task__c').getDescribe().getRecordTypeInfosByName().get('TO-DO').getRecordTypeId();
        String DailyRT = Schema.getGlobalDescribe().get('Task__c').getDescribe().getRecordTypeInfosByName().get('Daily').getRecordTypeId();
        
        Contact c = new Contact();
        c.LastName = 'Test Contact';
        insert c;

        List<Task__c> tasks = new List<Task__c>();
        Task__c t = new Task__c();
        t.Name = 'This is an Habit task';
        t.Difficulty__c = 'Easy';
        t.Status__c = 'Completed';
        t.RecordTypeId = HabitRT;
        t.Employee__c = c.Id;
        tasks.add(t);

        Task__c t2 = new Task__c();
        t2.Name = 'This is a ToDo task';
        t2.Difficulty__c = 'Easy';
        t2.Status__c = 'Completed';
        t2.RecordTypeId = TODORT;
        t2.Employee__c = c.Id;
        tasks.add(t2);

        Task__c t3 = new Task__c();
        t3.Name = 'This is a Daily task';
        t3.Difficulty__c = 'Easy';
        t3.Status__c = 'New';
        t3.RecordTypeId = DailyRT;
        t3.Employee__c = c.Id;
        tasks.add(t3);

        insert tasks;
    }

    @isTest
    private static void setTaskCompletedTest(){
        List<Task__c> tasks = [SELECT Id, Name, Status__c, RecordTypeId FROM Task__c WHERE RecordType.Name != 'Habit'];

        Test.startTest();
        CloseTaskTriggerHelper.setTaskCompleted(tasks);
        Test.stopTest();

        System.assertEquals(true, [SELECT Id, Task_Completed__c FROM Task__c WHERE RecordType.Name != 'Habit' AND Status__c = 'Completed' LIMIT 1].Task_Completed__c);
        System.assertEquals(false, [SELECT Id, Task_Completed__c FROM Task__c WHERE RecordType.Name != 'Habit' AND Status__c != 'Completed' LIMIT 1].Task_Completed__c);
    }

    @isTest
    private static void setPointsTotalTest(){
        List<Task__c> tasks = [SELECT Id, Name, Status__c, RecordTypeId, Employee__c, Points__c FROM Task__c];
        Contact c = new Contact();
        c.Id = tasks[0].Employee__c;
        c.Total_Points__c = 0;
        update c; // THIS IS NEEDED BECAUSE AFTER INSERT TASK TOTAL POINTS ARE ALREADY ASIGNED
        Test.startTest();
        CloseTaskTriggerHelper.setPointsTotals(tasks);
        Test.stopTest();
        Decimal totalPoints = (Decimal)[SELECT sum(Points__c) total FROM Task__c WHERE Status__c = 'Completed'][0].get('total');
        System.assertEquals(totalPoints, [SELECT Total_Points__c FROM Contact WHERE Id =: tasks[0].Employee__c].Total_Points__c);
    }

}