force-app/main/default/objects/Contact/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Points</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Habit_Failed__c.field-meta.xml
<CustomField>
    <fullName>Habit_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Habit Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <formula>CASE( RecordType.DeveloperName, 
&#39;TO_DO&#39;, (CASE( Difficulty__c , &#39;Trivial&#39;, 1, &#39;Easy&#39;, 2, &#39;Medium&#39;, 3, &#39;Hard&#39;, 5, 0))* IF( Overdue__c, 0.5, 1) , 
&#39;Daily&#39;, (CASE( Difficulty__c , &#39;Trivial&#39;, 0.5, &#39;Easy&#39;, 1, &#39;Medium&#39;, 1.5, &#39;Hard&#39;, 2.5, 0))* IF( Overdue__c, 0, 1), 
&#39;Habit&#39;, 1 - IF(  Habit_Failed__c, 2, 0), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Task_Completed__c.field-meta.xml
<CustomField>
    <fullName>Task_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Task Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TaskBoardController.cls
public with sharing class TaskBoardController {

    @AuraEnabled
    public static List<Task__c> getAllTasks(){
        return [SELECT Id, Name, Description__c, Difficulty__c, Points__c, Status__c, RecordType.Name, Task_Completed__c, Habit_Failed__c FROM Task__c WHERE Status__c != 'Completed'];
    }

    @AuraEnabled
    public static void setNewStatus(String taskId, String taskStatus){
        Task__c t = new Task__c();
        t.Id = taskId;
        t.Status__c = taskStatus;
        update t;
    }

    @AuraEnabled
    public static void setHabitPoints(String taskId, String taskAction){
        Task__c t = [SELECT Id, Employee__c, Points__c FROM Task__c WHERE Id =: taskId];
        Contact c = [SELECT Id, Total_Points__c FROM Contact WHERE Id =: t.Employee__c];
        if(c.Total_Points__c == NULL){
            c.Total_Points__c = 0;
        }
        if(taskAction == 'add'){
            c.Total_Points__c += t.Points__c;
            t.Task_Completed__c = true;
        }else if(taskAction == 'subtract'){
            c.Total_Points__c -= t.Points__c;
            t.Habit_Failed__c = true;
        }
        update c;
        update t;
    }
}